version: '3.8'
services:
  kenji:
    container_name: kenji
    build: .
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./settings.sqlite3:/app/settings.sqlite3
      - ./config.prod.json:/app/config.json